"""建 agent 运行库全部 16 张表

Revision ID: e02f04e7e6cf
Revises:
Create Date: 2026-09-16 13:49:50.697739
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "e02f04e7e6cf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_config",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("updated_by", sa.String(length=26), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_config")),
        sa.UniqueConstraint("key", "version", name="uk_agent_config_key_version"),
    )
    op.create_index("idx_agent_config_key_status", "agent_config", ["key", "status"], unique=False)
    op.create_table(
        "agent_conflict",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("evidence_ids_json", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("difference_json", sa.JSON(), nullable=True),
        sa.Column("explanations_json", sa.JSON(), nullable=True),
        sa.Column("resolution", sa.String(length=32), nullable=True),
        sa.Column("selected_basis", sa.Text(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_conflict")),
    )
    op.create_index(
        "idx_conflict_task_severity", "agent_conflict", ["task_id", "severity"], unique=False
    )
    op.create_table(
        "agent_conversation",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("user_id", sa.CHAR(length=26), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("context_summary_json", sa.JSON(), nullable=True),
        sa.Column("last_message_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_conversation")),
    )
    op.create_index(
        "idx_conversation_user_time",
        "agent_conversation",
        ["user_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "agent_evidence",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("tool_call_id", sa.CHAR(length=26), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("locator_json", sa.JSON(), nullable=True),
        sa.Column("event_time_start", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("event_time_end", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("metric_code", sa.String(length=64), nullable=True),
        sa.Column("definition_version", sa.String(length=32), nullable=True),
        sa.Column("scope_json", sa.JSON(), nullable=True),
        sa.Column("reliability", sa.String(length=16), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_evidence")),
    )
    op.create_index("idx_evidence_content_hash", "agent_evidence", ["content_hash"], unique=False)
    op.create_index(
        "idx_evidence_task_source", "agent_evidence", ["task_id", "source_type"], unique=False
    )
    op.create_table(
        "agent_finding",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("step_id", sa.CHAR(length=26), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("ruled_out_json", sa.JSON(), nullable=True),
        sa.Column("evidence_ids_json", sa.JSON(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_finding")),
    )
    op.create_index(
        "idx_finding_task_created", "agent_finding", ["task_id", "created_at"], unique=False
    )
    op.create_table(
        "agent_message",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("conversation_id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_message")),
    )
    op.create_index(
        "idx_message_conversation_time",
        "agent_message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_plan_revision",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("trigger_type", sa.String(length=16), nullable=False),
        sa.Column("trigger_finding_id", sa.CHAR(length=26), nullable=True),
        sa.Column("added_step_ids_json", sa.JSON(), nullable=True),
        sa.Column("skipped_step_ids_json", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("budget_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_plan_revision")),
        sa.UniqueConstraint("task_id", "revision_no", name="uk_plan_revision_no"),
    )
    op.create_table(
        "agent_review",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("round_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("coverage_score", sa.Float(), nullable=True),
        sa.Column("evidence_score", sa.Float(), nullable=True),
        sa.Column("consistency_score", sa.Float(), nullable=True),
        sa.Column("issues_json", sa.JSON(), nullable=True),
        sa.Column("missing_evidence_json", sa.JSON(), nullable=True),
        sa.Column("retry_target", sa.String(length=64), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_review")),
        sa.UniqueConstraint("task_id", "round_no", name="uk_review_round"),
    )
    op.create_table(
        "agent_task",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("parent_task_id", sa.CHAR(length=26), nullable=True),
        sa.Column("conversation_id", sa.CHAR(length=26), nullable=False),
        sa.Column("user_id", sa.CHAR(length=26), nullable=False),
        sa.Column("trace_id", sa.String(length=26), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=True),
        sa.Column("worker_id", sa.String(length=64), nullable=True),
        sa.Column("heartbeat_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("queued_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("plan_json", sa.JSON(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("final_answer_md", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("trace_incomplete", sa.Boolean(), nullable=False),
        sa.Column("started_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("finished_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_task")),
        sa.UniqueConstraint("trace_id", name="uk_task_trace"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uk_task_user_idempotency"),
    )
    op.create_index(
        "idx_task_status_heartbeat", "agent_task", ["status", "heartbeat_at"], unique=False
    )
    op.create_index("idx_task_status_updated", "agent_task", ["status", "updated_at"], unique=False)
    op.create_index("idx_task_user_created", "agent_task", ["user_id", "created_at"], unique=False)
    op.create_index("idx_task_worker", "agent_task", ["worker_id"], unique=False)
    op.create_table(
        "agent_task_step",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("step_key", sa.String(length=64), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=True),
        sa.Column("depends_on_json", sa.JSON(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("result_summary_json", sa.JSON(), nullable=True),
        sa.Column("started_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("finished_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("trigger_finding_id", sa.CHAR(length=26), nullable=True),
        sa.Column("drilldown_path_json", sa.JSON(), nullable=True),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("skipped_reason", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_task_step")),
        sa.UniqueConstraint("task_id", "step_key", name="uk_task_step_key"),
    )
    op.create_index(
        "idx_task_step_revision", "agent_task_step", ["task_id", "revision_no"], unique=False
    )
    op.create_table(
        "agent_tool_call",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("step_id", sa.CHAR(length=26), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("request_summary_json", sa.JSON(), nullable=True),
        sa.Column("normalized_sql", sa.Text(), nullable=True),
        sa.Column("sql_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("result_summary_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_call")),
    )
    op.create_index(
        "idx_tool_call_sql_fingerprint", "agent_tool_call", ["sql_fingerprint"], unique=False
    )
    op.create_index(
        "idx_tool_call_task_created", "agent_tool_call", ["task_id", "created_at"], unique=False
    )
    op.create_table(
        "agent_trace_event",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("task_id", sa.CHAR(length=26), nullable=False),
        sa.Column("trace_id", sa.String(length=26), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(length=64), nullable=True),
        sa.Column("tool", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_trace_event")),
        sa.UniqueConstraint("task_id", "sequence", name="uk_trace_event_sequence"),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("data_scope_json", sa.JSON(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("username", name=op.f("uq_app_user_username")),
    )
    op.create_index("idx_user_status", "app_user", ["status"], unique=False)
    op.create_table(
        "knowledge_document",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("logical_key", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("department", sa.String(length=64), nullable=True),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("allowed_roles_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=True),
        sa.Column("embedding_version", sa.String(length=32), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=26), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_document")),
        sa.UniqueConstraint("checksum", "version", name="uk_document_checksum_version"),
        sa.UniqueConstraint("logical_key", "version", name="uk_document_logical_version"),
    )
    op.create_index(
        "idx_document_status_effective",
        "knowledge_document",
        ["status", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "rag_vocab",
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("token_id", sa.BigInteger(), nullable=False),
        sa.Column("df", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_rag_vocab")),
        sa.UniqueConstraint("token_id", name="uk_vocab_token_id"),
    )
    op.create_table(
        "schema_catalog",
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("datasource", sa.String(length=64), nullable=False),
        sa.Column("tables_json", sa.JSON(), nullable=True),
        sa.Column("joins_json", sa.JSON(), nullable=True),
        sa.Column("metrics_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=26), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("published_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_catalog")),
        sa.UniqueConstraint("version", name="uk_schema_catalog_version"),
    )
    op.create_index("idx_schema_catalog_status", "schema_catalog", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_schema_catalog_status", table_name="schema_catalog")
    op.drop_table("schema_catalog")
    op.drop_table("rag_vocab")
    op.drop_index("idx_document_status_effective", table_name="knowledge_document")
    op.drop_table("knowledge_document")
    op.drop_index("idx_user_status", table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("agent_trace_event")
    op.drop_index("idx_tool_call_task_created", table_name="agent_tool_call")
    op.drop_index("idx_tool_call_sql_fingerprint", table_name="agent_tool_call")
    op.drop_table("agent_tool_call")
    op.drop_index("idx_task_step_revision", table_name="agent_task_step")
    op.drop_table("agent_task_step")
    op.drop_index("idx_task_worker", table_name="agent_task")
    op.drop_index("idx_task_user_created", table_name="agent_task")
    op.drop_index("idx_task_status_updated", table_name="agent_task")
    op.drop_index("idx_task_status_heartbeat", table_name="agent_task")
    op.drop_table("agent_task")
    op.drop_table("agent_review")
    op.drop_table("agent_plan_revision")
    op.drop_index("idx_message_conversation_time", table_name="agent_message")
    op.drop_table("agent_message")
    op.drop_index("idx_finding_task_created", table_name="agent_finding")
    op.drop_table("agent_finding")
    op.drop_index("idx_evidence_task_source", table_name="agent_evidence")
    op.drop_index("idx_evidence_content_hash", table_name="agent_evidence")
    op.drop_table("agent_evidence")
    op.drop_index("idx_conversation_user_time", table_name="agent_conversation")
    op.drop_table("agent_conversation")
    op.drop_index("idx_conflict_task_severity", table_name="agent_conflict")
    op.drop_table("agent_conflict")
    op.drop_index("idx_agent_config_key_status", table_name="agent_config")
    op.drop_table("agent_config")
    # ### end Alembic commands ###
